model = "gpt-5.3-codex"
# model = "anthropic/claude-sonnet-4.6"
# model = "openai/gpt-5.3-codex"
# model_provider = "openrouter"

model_reasoning_effort = "high"
hide_agent_reasoning = true
network_access = true
personality = "pragmatic"
web_search = "live"

[features]
streamable_shell = true          # enable the streamable exec tool

[mcp_servers.playwright]
command = "npx"
args = [ "@playwright/mcp@latest" ]

# [model_providers.openrouter]
# name = "Openrouter"
# base_url = "https://openrouter.ai/api/v1"
# env_key = "OPENROUTER_API_KEY"
