## status bar
set-option -g status-bg "colour238"
set-option -g status-fg "colour255"
# set-window-option -g window-status-format " #I: #W "
# set-window-option -g window-status-current-format " #I: #W #[default]"

### キーバインドの設定
## prefix
set -g prefix C-a
## デフォルトのprefixキーC-bを解除する
unbind C-b
## copy-mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi escape send-keys -X clear-selection

# set-option -g mouse on

### pane
## move pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
