#set-option -g default-shell /usr/bin/fish
set-option -g default-shell /bin/zsh
# status bar
# set-option -g status-bg "colour238"
# set-option -g status-fg "colour255"
set-option -g status-bg default
set-option -g status-style bg=default
# set-option -g status-style bg=default
set-option -g status-left '#[fg=red,bg=colour238]#{?client_prefix,#[reverse],} #[default]'
# set status tabbar style
set-window-option -g window-status-format '#[fg=#6699cc,bg=colour235] #I #[fg=#999999,bg=#2d2d2d] #W #[default]'
# Key bind setting
## set prefix key
set -g prefix C-a
## remove default prefix key (C-b)
unbind C-b
## copy-mode
set-window-option -g mode-keys vi
%if "$(uname | grep Linux)"
  ### for Ubuntu
  bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -ip && xsel -op | xsel -ib"
  bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xsel -ip && xsel -op | xsel -ib"
  bind ] run 'tmux set-buffer -- "$(xsel -b)"; tmux paste-buffer'
%else
  ### for Mac
  bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
  bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
%endif

bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi escape send-keys -X clear-selection

# pane
## move pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

## swap pane
bind H swap-pane -U
bind J swap-pane -U
bind L swap-pane -D
bind K swap-pane -D

## resize pane
bind C-h resize-pane -L 10
bind C-j resize-pane -D 10
bind C-k resize-pane -U 10
bind C-l resize-pane -R 10

## sync pane
bind e set-window-option synchronize-panes

## run shell in pane
bind S command-prompt -p "Send to all except nvim:" "run-shell \"~/work/sandbox/tools/tmux_send_to_all_except_nvim.sh '%%'\""
## split window
bind C-s split-window -c "#{pane_current_path}"
### already used h(horizontal) key, use b(beside)
bind C-v split-window -h -c "#{pane_current_path}"

## development
bind N split-window -h -c "#{pane_current_path}" \; \
  select-pane -L \; \
  send-keys 'nvim' C-m \; \
select-pane -R \; \
  split-window -v -c "#{pane_current_path}" \; \
  select-pane -U \; \
  send-keys 'claude' C-m \; \
  select-pane -D \; \
  send-keys 'gemini' C-m

# logging
## C-b C-p Start logging.
bind C-p pipe-pane -o '/bin/sh -c "while read -r LINE; do echo \"[\$(date +\"%%Y_%%m%%d_%%H%%M%%S_%%N\")] \${LINE}\" >> \${HOME}/.tmux/log/\$(date +%Y%m%d-%H%M%S)-#S-#I.#P.log; done "' \; display-message "Logging start."
## C-b C-o Stop logging
bind C-o pipe-pane \; display-message "Logging end."
## C-b v Open new window. Logging always. (-n is set window name.)
#bind v new-window -n 'logging...' \; pipe-pane -o '/bin/sh -c "while read -r LINE; do echo \"[\$(date +\"%%Y_%%m%%d_%%H%%M%%S_%%N\")] \${LINE}\" >> \${HOME}/.tmux/log/\$(date +%Y%m%d-%H%M%S)-#S-#I.#P.log; done "'

# create new window with current directory
bind c new-window -c "#{pane_current_path}"

set -g @plugin 'rose-pine/tmux'
set -g @plugin 'MunifTanjim/tmux-mode-indicator'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tpm'
set -g @rose_pine_variant 'moon'
set -g @rose_pine_status_left_prepend_section '#{tmux_mode_indicator}'
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_bar_bg_disabled_color_option 'default'

# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
run '~/.tmux/plugins/tpm/tpm'
