-- avante = require("avante")
-- avante.setup({
--   -- other config
--   -- The system_prompt type supports both a string and a function that returns a string. Using a function here allows dynamically updating the prompt with mcphub
--   system_prompt = function()
--     local hub = require("mcphub").get_hub_instance()
--     return hub:get_active_servers_prompt()
--   end,
--   -- The custom_tools type supports both a list and a function that returns a list. Using a function here prevents requiring mcphub before it's loaded
--   custom_tools = function()
--     return {
--       require("mcphub.extensions.avante").mcp_tool(),
--     }
--   end,
--   disabled_tools = {
--     "list_files",    -- Built-in file operations
--     "search_files",
--     "read_file",
--     "create_file",
--     "rename_file",
--     "delete_file",
--     "create_dir",
--     "rename_dir",
--     "delete_dir",
--     "bash",         -- Built-in terminal access
--   },
-- })
vim.keymap.set("n", "<leader>al", ":AvanteClear<cr>", { noremap = true, silent = true, desc = "Avante - clear chat" })
